INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (1, 'Hyperico perforatum 400 mg', 'Hierba De San Juan');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (2, 'Hyperico perforatum 60 ml', 'Hierba De San Juan');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (4, 'Harina de Vicia faba fermentada 1 g', 'Haba');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (5, 'Turnera difusa 75 mg', 'Damiana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (5, 'Tilia occidentalisa 75 mg', 'Tila');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (5, 'Ipomea stans 100 mg', 'Tumba Vaqueros');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (5, 'Valeriana officinallis 100 mg', 'Valeriana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (5, 'Excipiente C.B.P. 450 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (6, 'Pulsatilla vulgaris 75 mg', 'Pulsatilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (6, 'Tila platyphilia 75 mg', 'Tila');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (6, 'Pasiflora ciliata 125 mg', 'Pasiflora');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (6, 'Valeriana officinalis 125 mg', 'Valeriana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (7, 'Portulaca oleracea 150 mg', 'Verdolaga');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (7, 'Vicia faba 150 mg', 'Haba');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (7, 'Proteína aislada de soya 150 mg', 'Proteína Aislada De Soya');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (7, 'Lecitina 150 mg', 'Lecitina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (7, 'Cacao 150 mg', 'Cacao');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (7, 'Excipiente C.B.P. 1 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (8, 'Extracto de passiflora incarnata 20 ml', 'Pasiflora');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (8, 'Extracto de humulus lupulus 10 ml', 'Lúpulo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (8, 'Agua destilada C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (9, 'Valeriana officinalis 150 mg', 'Valeriana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (9, 'Salvia officinalis 150 mg', 'Salvia De Bolita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (9, 'Sericographis mohuitle 150 mg', 'Muitle');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (9, 'Ipomea stans 150 mg', 'Tumba Vaqueros');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (10, 'Thymus vulgaris 1.66 g', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (10, 'Ipomea stans 1.66 g', 'Tumba Vaqueros');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (10, 'Salvia officinalis 1.66 g', 'Salvia De Bolita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (11, 'Extracto de humulus lupulus al 15% 15 ml', 'Lúpulo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (11, 'Extracto de passiflora cilliata al 15% 15 ml', 'Pasiflora');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (11, 'Extracto de matricaria chamomilla al 20% 15 ml', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (11, 'Extracto de mentha piperita al 10% 15 ml', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (12, 'Extracto de ipomea stans al 10% 15 ml', 'Tumba Vaqueros');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (12, 'Extracto de chrysanthemuym parthenium al 15% 15 ml', 'Santa María');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (12, 'Extracto de salvia officinalis al 15% 15 ml', 'Salvia De Bolita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (12, 'Extracto de tilia platyphillia al 15% 15 ml', 'Tila');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (13, 'Extracto de viscum album al 10% 15 ml', 'Zapote Blanco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (13, 'Extracto de valeriana officinalis al 10% 15 ml', 'Valeriana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (13, 'Extracto de salvia officinalis al 10% 15 ml', 'Salvia De Bolita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (13, 'Extracto de sericographis mohuitle al 10% 15 ml', 'Muitle');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (14, 'Trigonella foenum graecum 166.5 mg', 'Alholva');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (14, 'Salvia officinalis 83.25 mg', 'Salvia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (15, 'Vainilla planifolia 125 mg', 'Vainilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (15, 'Zingiber officinale 125 mg', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (15, 'Croton salutaris 125 mg', 'Sangre De Drago');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (15, 'Angélica archangelica 125 mg', 'Angélica');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (16, 'Eleuterococcus sentiocosus 100 mg', 'Eleuterococco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (16, 'Smilax officinalis 100 mg', 'Zarzaparrilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (16, 'Plumeria acutifolia 100 mg', 'Cacaloxochitl');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (16, 'Glyzyrrhiza glabra 100 mg', 'Regaliz');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (16, 'Angélica archangelica 100 mg', 'Angélica');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (17, 'Polypodium vulgare 500 mg', 'Calaguala');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (19, 'Extracto de Eucalyptus globulus al 15% 15 ml', 'Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (19, 'Extracto de tecoma stans al 10% 15 ml', 'Tronadora');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (19, 'Extracto de cacalia decomposita al 10% 30 ml', 'Cortina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (20, 'Plumeria acutifolia 10 mg', 'Cacaloxochitl');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (20, 'Excipiente C.B.P. 100 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (21, 'Extracto fluido de marrubio vulgare 30 ml', 'Marrubio');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (21, 'Extracto fluido de rosmarinus officinalis 50 ml', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (21, 'Agua C.B.P. 220 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (22, 'Extracto de edum dendroideum 2 ml', 'Siempre Viva Menor');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (22, 'Excipiente C.B.P. 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (23, 'Arctium lappa 150 mg', 'Lampazo Mayor');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (23, 'Smilax aristolochiaefolia 150 mg', 'Zarzaparrilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (23, 'Sambucus nigra 150 mg', 'Sauco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (23, 'Excipiente C.B.P. 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (24, 'Extracto de caléndula officinalis 1.0 g', 'Caléndula');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (24, 'Extracto de atropa belladona 1.0 g', 'Belladona');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (24, 'Extracto de lavanda officinalis 1.0 g', 'Alhucema');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (24, 'Excipiente C.B.P. 100 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (28, 'A.E. de lavandula officinalis', 'Lavanda');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (28, 'A.E. de cedronella mexicana', 'Citronella');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (28, 'Excipiente solución hidroalcoholica C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (29, 'Amni viznaga 3 g', 'Espuma De Mar');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (29, 'Archillea millefolium 2 g', 'Milenrama');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (29, 'Glicerina 30 g', 'Glicerina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (29, 'Emulgade 65 ml', 'Emulgade');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (30, 'Extracto al 15% de eugenia caryophyllata 20 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (30, 'Extracto al 15% de silicea terra 20 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (30, 'Excipiente C.B.P. 60 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (31, 'Extracto de plantago mayor al 10% 20 ml', 'Llantén');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (31, 'Extracto de origanum mejorana al 10% 20 ml', 'Orégano');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (31, 'Extracto de Gnaphalium indicum al 10% 20 ml', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (32, 'Extracto de lobelia laxiflora al 10% 30 ml', 'Chilpanxochitl');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (33, 'Gnaphalium indicum 7 g', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (33, 'Heterotheca inuloides 7 g', 'Árnica Mexicana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (33, 'Piper sanctum 3 g', 'Acuyo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (34, 'A.E. de menta al 1%', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (34, 'A.E. de alcanfor al 1%', 'Alcanfor');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (34, 'A.E. de guayacol al 1%', 'Guayacol');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (34, 'A.E. de tomillo al 1%', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (34, 'Esencia de tolú al 5%', 'Tolú');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (34, 'Excipiente C.B.P. 100 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (35, 'Gnaphalium indicum 100 g', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (35, 'Equisetum arvense 150 mg', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (35, 'Matricaria chamomilla 150 mg', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (36, 'Extracto fluido de Gnaphalium indicum 50 ml', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (36, 'Extracto fluido de Equisetum arvense 50 ml', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (36, 'Extracto de Matricaria chamomilla 25 ml', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (36, 'Vehículo miel C.B.P 220 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (37, 'Extracto de fluido de sambucus nigra 20 ml', 'Sauco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (37, 'Extracto fluido de tilia cordata 20 ml', 'Tila');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (37, 'Extracto fluido de viola tricolor 20 ml', 'Pensamiento Silvestre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (37, 'Vehículo miel C.B.P 120 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (38, 'Extracto fluido de tropaeolum majus 10 ml', 'Capuchina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (38, 'Extracto fluido de erodium cicutarion 10 ml', 'Alfilerillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (38, 'A.E. de canela (cinnamomun zeylanicum) .200 ml', 'Canela');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (38, 'A.E. de clavo (eugenia caryophyllata) .200 ml', 'Clavo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (38, 'Solución hidroalcoholica C.B.P. 30 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (39, 'Extracto fluido de tropaeolum majus 20 ml', 'Capuchina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (39, 'Extracto fluido de erodium cicutarion 20 ml', 'Alfilerillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (39, 'A.E. de canela (cinnamomun zeylanicum) .200 ml', 'Canela');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (39, 'A.E. de clavo (eugenia caryophyllata) .200 ml', 'Clavo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (39, 'Solución hidroalcoholica C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (40, 'Extracto fluido de Salvia officinalis 4.5 ml', 'Salvia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (40, 'Extracto fluido de Eucalyptus globulus 3.0 ml', 'Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (40, 'Extracto fluido de Gnaphalium indicum 4.5 ml', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (40, 'Extracto fluido de Junniperus communis 4.5 ml', 'Enebro');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (40, 'Extracto fluido de Sambucus nigra 4.5 ml', 'Sauco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (40, 'Jarabe C.B.P. 30 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (41, 'Extracto fluido de Eucalyptus globulus 30 ml', 'Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (41, 'Extracto fluido de Plantago mayor 30 ml', 'Llantén');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (41, 'Extracto fluido de Foeniculum vulgare 30 ml', 'Hinojo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (41, 'Extracto fluido de Thymus serpyllum 30 ml', 'Serpol');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (41, 'Vehículo miel C.B.P 220 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (42, 'Myroxylon balsamum 10 ml', 'Esencia De Tolú');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (42, 'Eucalyptus globulus 10 ml', 'Esencia De Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (42, 'Styrax benzoin dryan 10 ml', 'Esencia De Benjuí');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (42, 'Lavandula officinalis 5 ml', 'Esencia De Alhucema');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (42, 'Mentha piperita 5 ml', 'Esencia De Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (42, 'Thymus vulgaris 5 ml', 'Esencia De Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (42, 'Vehículo C.B.P 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (43, 'Lavandula officinalis 200 mg', 'Alhucema');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (43, 'Eucalyptus globulus 200 mg', 'Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (43, 'Extracto de citrus vulgaris 3.0 ml', 'Limón');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (43, 'Mentha piperita 200 mg', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (43, 'Miel C.B.P 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (44, 'Extracto de Gentiana lutea 2 ml', 'Genciana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (44, 'Extracto de Sambucus nigra 2 ml', 'Sauco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (44, 'Extracto de Borago officinalis 2 ml', 'Borraja');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (44, 'Extracto de Salvia officinalis 2 ml', 'Salvia De Bolita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (44, 'Vehículo miel C.B.P. 60 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (45, 'Extracto de plantago mayor 25 ml', 'Llantén');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (45, 'Extracto de malva silvestre 100 ml', 'Malva Común');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (45, 'Excipiente C.B.P. 100 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (47, 'Mentha piperita 1.0 g', 'Mentol');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (47, 'Guaiacum sancus 1.6 g', 'Guayacol');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (47, 'Eucalyptus globulus 1.0 g', 'Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (47, 'Extracto blando de sambucus nigra 1.0 ml', 'Sauco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (47, 'Extracto blando de verbascum thapsus 1.0 ml', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (47, 'Miel de abeja C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (48, 'Extracto de Sambucus nigra al 15% 15 ml', 'Sauco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (48, 'Extracto de salvia officinalis al 10% 15 ml', 'Salvia De Bolita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (48, 'Extracto de Borago officinalis al 15% 15 ml', 'Borraja');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (48, 'Extracto de Eucalyptus globulus al 10% 15 ml', 'Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (49, 'Extracto de hedera helicic al 15% 30 ml', 'Hiedra');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (49, 'Extracto de Gnaphalium indicum al 15% 30 ml', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (50, 'Extracto de verbascum thapsus al 15% 15 ml', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (50, 'Extracto de equisetum arvense al 15% 15 ml', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (50, 'Extracto de matricaria chamomilla al 15% 15 ml', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (50, 'Extracto de salvia officinalis añ 15% 15 ml', 'Salvia De Bolita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (51, 'Extracto de malva silvestris al 15% 10 ml', 'Malva');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (51, 'Extracto de lobelia laxiflora al 10% 10 ml', 'Chilpanxochitl');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (51, 'Extracto de gnaphalium indicum al 10% 15ml', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (51, 'Extracto de eucalyptus globulus 15 ml', 'Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (51, 'Vehículo C.B.P 60 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (52, 'Peptina cítrica natural 20 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (52, 'Excipiente C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (53, 'Rosmarinus officinalis 133.33 mg', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (53, 'Psittacantus cannaris 133.33 mg', 'Alpiste');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (54, 'Extracto de cecropia obtusifolia 10 ml', 'Guarumbo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (54, 'Extracto de árnica mexicana 10 ml', 'Árnica');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (54, 'Extracto de crataegus oxyacantha 10 ml', 'Espino Blanco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (54, 'Extracto de chiranthodendon pentadactylon 10 ml', 'Flor De Manita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (54, 'A.E. de lavandula 1 ml', 'A.E. De Lavanda');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (54, 'A.E. de marjoram 1 ml', 'A.E. De Mejorana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (55, 'Chirathodendron pentadoctylon 150 mg', 'Flor De Manita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (55, 'Crataegus oxycantha 150 mg', 'Espino Albar');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (55, 'Casimiroa edulis 150 mg', 'Zapote Blanco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (56, 'Extracto de plumeria acutifolia 10 ml', 'Cacaloxochitl');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (56, 'Vehículo C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (57, 'Croton salutaris 450 mg', 'Sangre De Drago');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (57, 'Excipiente C.B.P. 1 comprimido', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (58, 'Angélica archangelica 100 mg', 'Angélica');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (58, 'Rosmarinus officinalis 200 mg', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (58, 'Trigonella foenum graecum 125 mg', 'Alholva');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (58, 'Hyssopus officinalis 75 mg', 'Hisopo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (59, 'Casimiroa edulis 150 mg', 'Zapote Blanco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (59, 'Crataegus oxycantha 150 mg', 'Espino Albar');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (59, 'Rhamnus frangula 100 mg', 'Frangula');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (59, 'Equisetum arvense 100 mg', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (59, 'Excipiente C.B.P. 550 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (60, 'Casimiroa edulis 50 ml', 'Zapote Blanco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (60, 'Quercus sempervirens 50 ml', 'Encino');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (60, 'Equisetum robustum 50 ml', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (61, 'Casimiroa edulis 150 mg', 'Zapote Blanco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (61, 'Quercus sempervirens 150 mg', 'Encino');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (61, 'Equisetum robustum 100 mg', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (62, 'Extracto fluido de Gnaphalium indicum 3.0 g', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (62, 'Extracto fluido de Salvia officinalis 3.0 g', 'Salvia De Bolita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (62, 'Extracto fluido de thymus vulgaris 3.0 g', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (62, 'Extracto de heterotheca inuloides 3.0 g', 'Árnica Mexicana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (62, 'Excipiente C.B.P. 65 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (63, 'Extracto fluido de Gnaphalium indicum 3.0 g', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (63, 'Extracto fluido de Salvia officinalis 3.0 g', 'Salvia De Bolita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (63, 'Extracto fluido de thymus vulgaris 3.0 g', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (63, 'Extracto de heterotheca inuloides 3.0 g', 'Árnica Mexicana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (64, 'E.F. de catharantus roseus 3 ml', 'Vinca Rosea');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (64, 'E.F. de rosmarinus officialis 1 ml', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (64, 'E.F. de ginkgo biloba 3 ml', 'Ginkgo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (64, 'E.F. de eleuterococcus sentiocosus 2 ml', 'Eleuterococco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (65, 'Glutamato de sodio 83.33 mg', 'Glutamato De Sodio');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (65, 'Turnera difusa 83.33 mg', 'Damiana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (65, 'Valeriana officinalis 83.33 mg', 'Valeriana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (65, 'Zingiber officinalis 83.33 mg', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (65, 'Salvia officinalis 83.33 mg', 'Salvia De Bolita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (65, 'Mentha piperita 83.33 mg', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (66, 'Betula pendula 75 mg', 'Abedul');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (66, 'Zea maís 75 mg', 'Maíz');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (66, 'Equisetum arvense 75 mg', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (66, 'Casimiroa edulis 75 mg', 'Zapote Blanco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (66, 'Crataegus oxycantha 150 mg', 'Espino Albar');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (67, 'Melissa officinalis 166.6 mg', 'Melisa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (67, 'Ruta graveolens 166.6 mg', 'Ruda');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (67, 'Matricaria chamomilla 166.6 mg', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (68, 'Cada 10 ml contienen: Extracto de alium sativum al 3%', 'Ajo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (69, 'Verbascum thapsus 200 mg', 'Gordolobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (69, 'Urtica dioica 100 mg', 'Ortiga Mayor');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (69, 'Cupresus serpevirens 100 mg', 'Ciprés');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (69, 'Agastache mexicana 75 mg', 'Toronjil');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (70, 'Cada 100 ml contienen: Extracto de Jacquemontia evolvuloides 20 ml', 'Correhuela');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (70, 'Cada 100 ml contienen: Vehículo C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (71, 'Extracto de hammamelis virginiana al 15% 40 ml', 'Hammamelis');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (71, 'Extracto de cupresus sempervirens al 15% 40 ml', 'Ciprés');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (71, 'Extracto de croton salutaris al 15% 40 ml', 'Sangre De Drago');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (72, 'Mussa sapietum 1 g', 'Planta De Plátano');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (73, 'Extracto al 30% de hibiscum sabdariffa 60 ml', 'Jamaica');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (74, 'Extracto de crotton salutaris al 20% 30 ml', 'Sangre De Drago');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (74, 'Extracto de capsicum annum al 5% 30 ml', 'Cayene');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (75, 'Extracto de zea mays al 10% 10 ml', 'Pelo De Elote');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (75, 'Extracto de betula pendula al 10% 10 ml', 'Abedul');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (75, 'Extracto de crataegus oxyacantha al 10% 15 ml', 'Espino Blanco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (75, 'Extracto de cynara scolymus al 10% 15 ml', 'Alcachofa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (75, 'Extracto de psyllium plantago al 10% 10 ml', 'Zaragatona');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (76, 'Extracto de crataegus oxycantha al 15% 15 ml', 'Espino Albar');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (76, 'Extracto de viscum album al 15% 15 ml', 'Muérdago');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (76, 'Extracto de casimiroa edulis al 10% 15 ml', 'Zapote Blanco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (76, 'Extracto de achillea millefolium al 15% 15 ml', 'Milenrama');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (77, 'Peumus boldus 100 mg', 'Boldo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (77, 'Marsdenia cundurango 100 mg', 'Condurango');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (77, 'Menta piperita 100 mg', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (77, 'Cynara scolymus 100 mg', 'Alcachofa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (77, 'Equisetum arvense 100 mg', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (78, 'Linum usitatissinum 150 mg', 'Lino');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (78, 'Angélica archangelica 150 mg', 'Angélica');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (78, 'Pimpinela anisum 100 mg', 'Anís');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (78, 'Matricaria chamomilla 100 mg', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (78, 'Excipiente C.B.P. 600 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (79, 'Peumus boldus 125 mg', 'Boldo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (79, 'Rosmarinus officialis 125 mg', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (79, 'Matricaria chamomilla 125 mg', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (79, 'Pimpinela anisum 75 mg', 'Anís');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (80, 'Extracto fluido de menta piperita 10 ml', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (80, 'Extracto fluido de melissa officnalis 10 ml', 'Melisa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (80, 'Extracto fluido de rosmarinus officinalis 10 ml', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (80, 'Extracto fluido de valeriana officinalis 10 ml', 'Valeriana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (80, 'Vehículo miel C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (81, 'Menta piperita 100 mg', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (81, 'Melissa officinalis 100 mg', 'Melisa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (81, 'Rosmarinus officinalis 100 mg', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (81, 'Valeriana officinales 100 mg', 'Valeriana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (82, 'Vaccinium myrtillus 150 mg', 'Arándano');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (82, 'Linum usitatissinum 150 mg', 'Lino');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (82, 'Piqueria trinervia 150 mg', 'Hierba Del Tabardillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (82, 'Excipiente C.B.P. 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (83, 'Castela tortuosa 125 mg', 'Chaparro Amargo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (83, 'Mentha piperita 125 mg', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (83, 'Ambrosia psilostachya 125 mg', 'Altamisa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (83, 'Semilla cucurbita pepo 125 mg', 'Semilla De Calabaza');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (84, 'Zingiber officinalis 150 mg', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (84, 'Salvia officinalis 150 mg', 'Salvia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (84, 'Spigelia longiflora 150 mg', 'Hierba Del Burro');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (84, 'Excipiente C.B.P. 600 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (85, 'Arracacia atropurpurea 100 mg', 'Comino');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (85, 'Matricaria chamomilla 150 mg', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (85, 'Pimpinella anisum 150 mg', 'Anís');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (85, 'Foeniculum vulgare 100 mg', 'Hinojo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (86, 'Trigonella foenum graecum 150 mg', 'Alholva');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (86, 'Plumeria acutifolia 175 mg', 'Cacaloxochitl');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (87, 'Jacquemontia evolvuloides 450 mg', 'Correhuela');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (89, '', 'Clorofila');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (89, '', 'Bicarbonato De Sodio');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (89, '', 'A.E. De Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (89, 'Excipiente C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (90, 'Fluorensia cernua 125 mg', 'Hojas De Sen');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (90, 'Rhamnus pursaniana 125 mg', 'Cáscara Sagrada');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (91, 'Extracto fluido de psyllium plantago', 'Zaragatona');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (91, 'Rhamus frangula al 50%', 'Frangula');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (91, 'Vehículo miel C.B.P. 30ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (92, 'Cada 100 ml contiene: Linum usitassimmun 10 g', 'Lino');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (92, 'Excipiente C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (93, 'Equisetum arvense 50 mg', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (93, 'Pimpinella anisum 50 mg', 'Anís');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (93, 'Foeniculum vulgare 50 mg', 'Hinojo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (93, 'Arctium lappa 50 mg', 'Lampazo Mayor');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (93, 'Smilax aristolochiaefolia 50 mg', 'Zarzaparrilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (94, 'Extracto fluido de matricaria chamomilla 5 ml', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (94, 'Extracto fluido de thymus vulgaris 5 ml', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (94, 'Extracto fluido de melissa officnalis 5 ml', 'Melisa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (94, 'Extracto fluido de pimpinella anisum 5 ml', 'Anís');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (94, 'Vehículo miel C.B.P 30 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (96, 'Psidium guajava 250 mg', 'Guayabo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (96, 'Quercus sempervirens 250 mg', 'Encino');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (96, 'Matricaria chamomilla 100 mg', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (97, 'Extracto fluido de psidium guajava 50 ml', 'Guayabo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (97, 'Extracto fluido de quercus sempervirens 50 ml', 'Encino');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (97, 'Extracto fluido de matricaria chamomilla 25 ml', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (97, 'Vehículo miel C.B.P. 220 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (98, 'Cynara scolymus 100 mg', 'Alcachofa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (98, 'Peumus boldus 150 mg', 'Boldo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (98, 'Conyza filaginoides 150 mg', 'Simonillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (98, 'Quassia amara 75 mg', 'Cuasia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (99, 'Castela tortuosa al 15% 30 ml', 'Chaparro Amargo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (99, 'Chenopodium ambrosioides al 10% 30 ml', 'Altamisa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (100, 'Peumus boldus al 15% 15 ml', 'Boldo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (100, 'Cynara scolymus al 15% 15 ml', 'Alcachofa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (100, 'Selaginella lepidophylla al 10% 15 ml', 'Doradilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (100, 'Quassia amara al 10% 15 ml', 'Cuasia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (101, 'Extracto de equisetum arvense al 15% 10 ml', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (101, 'Extracto de pimpinella anisum al 10% 10 ml', 'Anís Verde');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (101, 'Extracto de mentha piperita al 10% 10 ml', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (101, 'Extracto de Glyzyrrhiza lepidota al 15% 10 ml', 'Orozuz');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (101, 'Extracto de lappa major al 20% 10 ml', 'Lampazo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (101, 'Extracto de srnilax aristolochiaefolia al 10% 10 ml', 'Zarzaparrilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (102, 'Medicago sativa 250 mg', 'Alfalfa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (102, 'Levadura de cerveza 250 mg', 'Levadura De Cerveza');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (102, 'Miel 100 mg', 'Miel De Abeja');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (103, 'Extracto fluido de gentiana lutea 20 ml', 'Genciana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (103, 'Extracto fluido de peumus boldus 20 ml', 'Boldo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (103, 'Extracto fluido de ambrosia psitolachya 20 ml', 'Altamisa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (103, 'Alcohol 6 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (103, 'Jarabe C.B.P. 220 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (104, 'Extracto fluido de urtica dioica 60 ml', 'Ortiga');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (104, 'Extracto fluido de gentiana lutea 60 ml', 'Genciana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (104, 'Vehículo miel 220 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (105, 'Avena sativa 100 mg', 'Avena');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (105, 'Hordeum vulgare 100 mg', 'Cebada');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (105, 'Triticum sativum 100 mg', 'Trigo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (105, 'Oryza sativa 100 mg', 'Arroz');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (105, 'Secale cereale 100 mg', 'Centeno');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (105, 'Medicago sativa 100 mg', 'Alfalfa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (105, 'Lithospernun officialis 100 mg', 'Mijo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (106, 'Tilia cordata 100 mg', 'Tila');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (106, 'Valeriana officinalis 100 mg', 'Valeriana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (106, 'Rhamnus frangula 100 mg', 'Frangula');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (106, 'Lecitina 100 mg', 'Lecitina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (106, 'Smilax rotundifolia 100 mg', 'Zarzaparrilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (107, '', 'Harina De Granos Germinados Pulverizados');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (108, '', 'Polen');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (108, '', 'Miel De Abeja');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (109, '', 'Miel De Abeja');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (109, '', 'Polen');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (109, '', 'Ácido Ascórbico');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (110, '', 'Proteína Aislada De Soya');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (110, '', 'Suero De Leche');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (110, '', 'Cocoa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (110, '', 'Edulcorantes');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (111, 'Jalea real 25 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (111, 'Palmitato 50,000 U.I', 'Vitamina A');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (111, 'Ácido ascórbico 80 mg', 'Vitamina C');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (111, 'Acetato de alfa tocoferol 30 mg', 'Vitamina E');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (111, 'Clohidrato de tiamina 3 mg', 'Vitamina B1');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (111, 'Riboflavina 2 mg', 'Vitamina B2');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (111, 'Piridoxina, clorhidrato 2 mg', 'Vitamina B6');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (111, 'Cianocobalamina', 'Vitamina B12');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (111, 'Niacinamida 24 mg', 'Niacinamida');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (111, 'D-Pantenol 10 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (111, 'Miel C.B.P. 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (112, 'Cada 100 ml contiene: Extracto de medicago sativa al 10% 20 ml', 'Alfalfa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (112, 'Cada 100 ml contiene: Extracto de urtica dioica al 10% 20 ml', 'Ortiga Mayor');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (112, 'Cada 100 ml contiene: taraxacum officinale al 10% 20 ml', 'Diente De León');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (112, 'Jarabe C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (113, 'Retinol 1,000 U.I', 'Palmitato De Vitamina A');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (113, 'Ácido ascórbico 250 mg', 'Vitamina C');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (113, 'Ergocalciferol 10 U.I', 'Vitamina D2');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (113, 'Clohidrato de tiamina 5 mg', 'Vitamina B1');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (113, 'Clohidrato de rivoflavina 2 mg', 'Vitamina B2');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (113, 'Clohidrato de piridoxina 1 mg', 'Vitamina B6');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (114, 'Cuphea aequipetala 124 mg', 'Hierba De Cáncer');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (114, 'Hypericum pratense 84 mg', 'Tenchalita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (114, 'Jacobinia spicigera 84 mg', 'Muicle');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (114, 'Smilax aristolochiaefolia 84 mg', 'Zarzaparrilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (114, 'Malvaviscus candidus 124 mg', 'Malvavisco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (115, '', 'Clorofila');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (115, '', 'Vitamina E');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (116, 'Eucalyptus globulus 112.5 mg', 'Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (116, 'Salvia officinalis 112.5 mg', 'Salvia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (116, 'Pulmonaria officinalis 112.5 mg', 'Pulmonaria');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (117, 'Betacaroteno', 'Vitamina A');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (117, '', 'Ascorbato De Sodio');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (117, '', 'Vitamina E');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (117, '', 'Bioflavonoides');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (117, 'Vehículo de miel C.B.P. 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (118, 'Taraxacum officinale 100 mg', 'Diente De León');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (118, 'Trifolium repens 100 mg', 'Trévol');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (118, 'Salvia officnalis 100 mg', 'Salvia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (118, 'Pulmonaria officinalis 100 mg', 'Pulmonaria');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (118, 'Thymus vulgaris 100 mg', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (121, 'Mentha piperita 100mg', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (121, 'Arctium lappa 100 mg', 'Bardana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (121, 'Taraxacum officinale 100 mg', 'Diente De León');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (121, 'Petroselinum crispum 100 mg', 'Perejil');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (121, 'Magnolia grandiflora 100 mg', 'Magnolia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (121, 'Vitamina C 100 mg', 'Vitamina C');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (122, 'Catharanthus roseus 250 mg', 'Vinca Rosea');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (122, 'Casimiroa edulis 250 mg', 'Zapote Blanco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (126, 'Extracto de eleuterococcus sentiocosus al 15% 15 ml', 'Eleuterococco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (126, 'Extracto de salvia officinales al 15% 15 ml', 'Salvia De Bolita');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (126, 'Extracto de pulmonaria al 20% 15 ml', 'Pulmonaria');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (126, 'Extracto de taraxacum officinale al 20% 15 ml', 'Diente De León');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (127, 'Valeriana officinalis 100 mg', 'Valeriana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (127, 'Matricaria chamomilla 100 mg', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (127, 'Foeniculum vulgare 200 mg', 'Hinojo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (127, 'Polypodium vulgare 100 mg', 'Calaguala');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (128, 'Turnera difusa 15 ml', 'Damiana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (128, 'Rosmarinus officinalis 5 ml', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (128, 'Menta piperita 5 ml', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (128, 'Zingiber officinalis 3 ml', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (128, 'Croton salutaris 2 ml', 'Sangre De Drago');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (129, 'Turnera difusa 90 mg', 'Damiana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (129, 'Rosmarinus officinalis 90 mg', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (129, 'Thymus vulgaris 90 mg', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (129, 'Mentha piperita 90 mg', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (130, 'Casimiroa edulis 150 mg', 'Zapote Blanco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (130, 'Pimpinella anisum 150 mg', 'Anís');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (130, 'Humulus lupulus 150 mg', 'Lúpulo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (130, 'Matricaria chamomilla 150 mg', 'Manzanilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (131, 'Arctostapylus uva ursi 125 mg', 'Gayuba');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (131, 'Eleuterococcus sentiocosus 125 mg', 'Eleuterococco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (131, 'Juniperus communis 125 mg', 'Enebro');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (131, 'Zingiber officinale 75 mg', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (132, 'Arbustus unedo 150 mg', 'Madroño');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (132, 'Plantago mayor 100 mg', 'Llantén');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (132, 'Juniperus communis 100 mg', 'Enebro');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (132, 'Arctostapylus uva ursi 150 mg', 'Gayuba');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (133, 'Equisetum arvense 100 mg', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (133, 'Arctostaphylus uva ursi 100 mg', 'Gayuba');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (133, 'Selaginella lepidophylla 100 ml', 'Doradilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (133, 'Petroselinum sativum 100 mg', 'Perejil');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (134, 'Eysenhardtia repens 100 mg', 'Taray');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (134, 'Althernantera lepidophylla 100 mg', 'Tianguispepetla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (134, 'Sellaginela lepidophylla 100 mg', 'Doradilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (135, 'Vinagre de manzana 100 ml', 'Vinagre De Manzana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (135, 'Extracto de hammamelis virginiana 100 ml', 'Hammamelis');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (135, 'Jarabe C.B.P. 220 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (136, 'Extracto de arbustus unedo al 12% 15 ml', 'Madroño');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (136, 'Extracto de Arctostaphylus uva ursi al 12% 15 ml', 'Gayuba');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (136, 'Extracto de Juniperus communis al 12% 15 ml', 'Enebro');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (136, 'Extracto de betula pendula al 12% 15 ml', 'Abedul');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (137, 'Extracto de zingiber offcinalis al 10% 15 ml', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (137, 'Extracto de turnera difusa al 15% 15 ml', 'Damiana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (137, 'Extracto de ginkgo biloba al 15% 15 ml', 'Ginkgo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (137, 'Extracto de eleuterococcus sentiocosus al 10% 15 ml', 'Eleuterococco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (138, 'Plumeria acutifolia 150 mg', 'Cacaloxochitl');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (138, 'Thymus vulgaris 150 mg', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (140, 'Heterotheca inuloides 240 mg', 'Árnica Mexicana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (141, 'Rosmarinus officinalis 83.33 mg', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (141, 'Zingiber officinale 83.33 mg', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (141, 'Mentha piperita 83.33 mg', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (141, 'Gaultheria acuminata 83.33 mg', 'Axocopaque');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (142, 'Cada 100 g contiene: Extracto fluido de heterotheca inuloides 2 ml', 'Árnica Mexicana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (142, 'Cada 100 g contiene: Extracto fluido de gaultheria acuminata 3 ml', 'Axocopaque');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (142, 'Cada 100 g contiene: Extracto fluido de urtica dioica 5 ml', 'Ortiga Mayor');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (142, 'Cada 100 g contiene: Extracto fluido de rosmarinus officinalis 5 ml', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (142, 'Eucalyptus globulus 50 mg', 'Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (142, 'Excipiente C.B.P. 100 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (143, 'Extracto de heterotheca inuloides 100 ml', 'Árnica Mexicana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (143, 'Extracto de harpagophytum procumbens 10 ml', 'Harpagophyto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (143, 'Extracto de gaultheria acuminata 10 ml', 'Axocopaque');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (143, 'A.E. de mentol 2 g', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (143, 'A.E. de eucalioptol 2 g', 'Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (143, 'A.E. de guayacol 2 g', 'Guayacol');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (144, 'Achillea millefolium 150 mg', 'Milenaria');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (144, 'Plumeria acutifolia 200 mg', 'Cacaloxochitl');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (144, 'Equisetum arvense 150 mg', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (145, 'Trementina 2 g', 'Trementina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (145, 'Gaultheria procumbers 2 g', 'Axocopaque');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (145, 'Aceite de linum usitatissinum 10 ml', 'Lino');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (145, 'Datura arborea 2 g', 'Floripondio');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (146, 'Capriola dactylon 125 mg', 'Grama');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (146, 'Zea mais 125 mg', 'Maíz');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (146, 'Betula pendula 125 mg', 'Abedul');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (146, 'Vitis tileacea 125 mg', 'Tripa De Judas');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (147, 'Extracto de gaultheria acuminata al 10% 15 ml', 'Axocopaque');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (147, 'Extracto de rosmarinus officinalis al 15% 15 ml', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (147, 'Extracto de harpagophytum procumbens al 15% 15 ml', 'Harpagophyto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (147, 'Extracto de taxodium mucronatum al 10% 15 ml', 'Ahuehuete');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (148, 'Extracto de gaultheria acuminata al 10% 10 ml', 'Axocopaque');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (148, 'Extracto de rosmarinus officinalis al 15% 10 ml', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (148, 'Extracto de harpagophytum procumbens al 15% 15 ml', 'Harpagophyto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (148, 'Extracto de heterotheca inuloides al 10% 10 ml', 'Árnica Mexicana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (148, 'Extracto de plumeria acutifolia 15 ml', 'Cacaloxochitl');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (149, '', 'Grenetina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (149, '', 'Vitamina C');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (149, '', 'Espirulina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (149, '', 'Vitamina E');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (149, 'Excipiente C.B.P. 450 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (150, 'Ilex paraguariensis 160 mg', 'Té Mate');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (150, 'Pimpinella annisum 160 mg', 'Anís');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (151, 'Zingiber officinale 100 mg', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (151, 'Trigonella foenum graecum 100 mg', 'Alholva');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (151, 'Mentha piperita 100 mg', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (151, 'Polen 100 mg', 'Polen');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (152, 'Thymus vulgaris 80 mg', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (152, 'Salvia officinalis 80 mg', 'Salvia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (152, 'Mentha piperita 80 mg', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (152, 'Melissa officinalis 80 mg', 'Melisa');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (153, 'Extracto de zingiber offcinalis al 15% 5 ml', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (153, 'Extracto de Glyzyrrhiza lepidota al 10% 5 ml', 'Orozuz');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (153, 'Extracto de zyzygium aromaticum al 5% 5 ml', 'Clavo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (153, 'Extracto de cinnamomum zaylanicum al 15% 5 ml', 'Canela');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (153, 'Extracto de piper nigrum al 10% 5 ml', 'Pimienta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (153, 'Vehículo C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (154, 'Extracto de eleuterococcus al 10% 5ml', 'Eleuterococco');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (154, 'Extracto de glycyrriza lepidota al 10% 5 ml', 'Orozuz Americano');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (154, 'Extracto de mentha piperita al 10% 5 ml', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (154, 'Extracto de zingiber officinalis al 10% 5 ml', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (154, 'Polen 500 mg', 'Polen');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (154, 'Vehículo C.B.P. 100 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (155, 'Extracto de zingiber officinalis al 5% 10 ml', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (155, 'Extracto de mentha piperita al 20% 15 ml', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (155, 'Extracto de ilex paraguariensis al 10% 20 ml', 'Té Mate');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (155, 'Extracto de angelica archangelica al 10% 15 ml', 'Angélica');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (156, 'Alga espirulina 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (156, 'Excipiente C.B.P. 550 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (157, '', 'Salvado De Trigo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (157, '', 'Salvado De Arroz');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (157, '', 'Semilla De Lino');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (157, '', 'Psillium Plantago');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (158, 'Harina de soya fermentada 1 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (158, 'Excipiente C.B.P. 1.1 G', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (159, 'Harina de germen de trigo 1 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (159, 'Excipiente C.B.P. 1.1 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (160, 'Helianthus annus 50 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (160, 'Jarabe de azúcar', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (160, 'Mascabado C.B.P. 100 G', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (162, 'Suero de leche en polvo 1 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (162, 'Excipiente C.B.P. 1.2 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (164, 'L-lisina 1g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (164, 'Excipiente C.B.P. 1.100 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (165, 'Albúmina de huevo desecada 1 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (165, 'Excipiente C.B.P. 1.1 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (166, 'Harina de trébol rojo germinado 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (166, 'Excipiente C.B.P. 550 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (167, 'Extracto al 10% de heterotheca inuloides', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (168, '', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (168, '', 'Clavo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (168, '', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (168, 'Excipiente C.B.P. 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (169, '', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (169, '', 'Clavo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (169, '', 'Jengibre');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (170, 'Extracto al 20% de persea gratissima', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (170, 'Extracto al 20% de harpagophytum procumbens', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (171, 'Malva silvestris 300 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (171, 'Marrubium vulgare 300 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (171, 'Trigonella foenum graecum 300 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (171, 'Excipiente C.B.P. 1 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (172, 'Extracto al 10% de vicia faba', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (172, 'Extracto al 10% de curbubita pepo', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (172, 'Extracto al 10% de helianthus annus', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (173, 'Extracto de zingiber officinalis al 10%', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (174, 'Trigonella foenum graecun 260 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (174, 'Salvia officinalis 260 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (174, 'Phaseolus communis 260 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (174, 'Excipiente C.B.P. 1 cmpdo.', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (175, 'Cúrcuma longa 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (175, 'Excipiente C.B.P. 1 cmpd.', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (176, 'Schisandra chinensis 200 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (176, 'Eleuterococcus sentiocosus 200 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (176, 'Ginkgo biloba 200 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (176, 'Leticina 100 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (176, 'Alga espirulina 100 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (176, 'Excipiente C.B.P. 1 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (177, 'Extracto al 10% de schisandra chinensis', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (177, 'Extracto al 10% de eleuterococcus sentiocosus', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (177, 'Extracto al 10% de ginkgo biloba', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (177, 'Extracto al 10% de leticina', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (177, 'Extracto al 10% de alga espirulina', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (178, '', 'Licopodio');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (178, '', 'Romero');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (178, '', 'Anís');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (178, '', 'Salvia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (178, '', 'Ortiga');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (178, '', 'Gotukola');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (178, '', 'Lecitina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (178, '', 'Colina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (179, 'Extracto concentrado al 20% de camelia sinensis 50 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (180, 'Extracto al 10% de etheroteca inuloides 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (180, 'Extracto al 10% de caléndula officinalis 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (180, 'Extracto al 10% de hamamelis virginiana 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (180, 'Extracto al 10% de matricaria chamomilla 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (180, 'Extracto al 10% de hypericum perforatum 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (181, 'Extracto al 10% de etheroteca inuloides 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (181, 'Extracto al 10% de caléndula officinalis 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (181, 'Extracto al 10% de hamamelis virginiana 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (181, 'Extracto al 10% de matricaria chamomilla 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (181, 'Extracto al 10% de hypericum perforatum 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (182, 'Jugo natural de portulaca oleracea 200 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (182, 'Gel de linnum usitasimun 50 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (183, '', 'Milenrama');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (183, '', 'Pasiflora');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (183, '', 'Ortiga');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (183, '', 'Árnica Mexicana');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (183, '', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (184, '', 'Arcilla');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (184, '', 'Bicarbonato De Sodio');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (184, 'Excipiente C.B.P. 1 cmpdo.', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (185, 'Annona muricata 700 mg', 'Graviola');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (185, 'Excipiente C.B.P. 750 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (186, 'Pimpinella anisum 12.6 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (186, 'Medicago sativa 12.6 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (186, 'Tilia cordata 12.6 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (186, 'Melissa officinalis 12.6 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (186, 'Matricaria chamomilla 12.6', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (186, 'Lecitina 12.6 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (186, 'Arctostaphylos pungens 12.6 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (186, 'Levadura de cerveza 12.6 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (186, 'L-Metionina 10 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (186, 'L-Colina 6 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (186, 'Inositol 4 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (187, 'Tropaeolum majus 200 mg', 'Capuchina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (187, 'Thymus vulgares 100 mg', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (187, 'Salvia officinalis 100 mg', 'Salvia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (187, 'Glycyrryza glabra 75 mg', 'Orozuz');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (188, 'Extracto al 20% de Tropaeolum majus', 'Capuchina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (188, 'Extracto al 20% de Thymus vulgares', 'Tomillo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (188, 'Extracto al 20% de Salvia officinalis', 'Salvia');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (188, 'Extracto al 20% de Glycyrryza glabra', 'Orozuz');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (189, '', 'Levadura De Cerveza Desamargada');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (190, 'Extracto concentrado al 10% de prunus pérsica 60 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (191, 'Mezcla de harina de granos germinados en polvo 350 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (191, 'Goma guar 100 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (192, 'Coffea cruda 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (193, 'Extracto concentrado al 20% de zingiber officinalis 30 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (193, 'Angélica archangelica 30 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (194, 'Sericographis mohuitle 200 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (194, 'Foeniculum vulgare 200 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (194, 'Matricaria chamomilla 200 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (194, 'Valeriana officinalis 200 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (194, 'Angélica archangelica 200 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (195, 'Ácido lipóico 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (195, 'Ácido abscórbico 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (196, '', 'Ácido Alfalipoico');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (196, '', 'Ester De Vitamina C');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (196, '', 'Vitamina E');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (196, '', 'Lecitina');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (197, 'Extracto al 20% de taraxacum offcinalis 20 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (197, 'Tecojote 30 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (197, 'Excipiente C.B.P. 60 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (198, '', 'Aceite De Oliva');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (198, '', 'Viragin');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (199, 'Arctium lappa 250 mg', 'Lampazo Mayor');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (199, 'Taraxacum officinale 250 mg', 'Diente De León');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (199, 'Equisetum arvense robustum 250 mg', 'Cola De Caballo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (199, 'Ceratonia siliqua 250 mg', 'Algarrobo');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (200, 'Harina de Vicia faba 350 g', 'Harina De Haba');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (200, 'Harina de Curcubita pepo 350 g', 'Harina De Calabaza');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (200, 'Harina de Helianthus annus 200 g', 'Harina De Girasol');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (200, 'Excipiente C.B.P. 1 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (201, '', 'Fibra De Semilla De Girasol');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (202, 'Alga clorella 400 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (202, 'Clorofila 100 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (202, 'Thymus vulgaris 100 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (202, 'Menta 100 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (202, 'Rosmarinus officinalis 100 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (202, 'Eleutherococcus senticosus 100 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (202, 'Excipiente C.B.P. 1 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (203, 'Extracto al 10% de atropa belladona 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (203, 'Extracto de salvia officinalis 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (203, 'Extracto de thymus vulgaris 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (203, 'Extracto de llantén 20 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (203, 'Extracto de cayene 10 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (203, 'Extracto de hipericum perforatum 20 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (203, 'Extracto de achillea millefolium 20 ml', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (204, 'Sábila 35 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (204, 'Excipiente C.B.P. 100 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (205, 'Fibra de chía 100 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (206, 'Aceite de chía contemnido omega 3 al 38%', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (207, 'Extracto concentrado al 10% de arctostaphylos uva-ursi', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (207, 'Extracto concentrado al 10% de quassia amara', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (207, 'Extracto concentrado al 10% de sabal serulata', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (207, 'Extracto concentrado al 10% de equisetum arvense robustum', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (207, 'Extracto concentrado al 10% de vinagre de manzana', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (208, 'Extracto concentrado al 10% de arctium lappa', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (208, 'Extracto concentrado al 10% de trifolium pratense', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (208, 'Extracto concentrado al 10% de cynara cardunculus', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (208, 'Extracto concentrado al 10% de vinagre de manzana', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (209, 'Sales efervescentes', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (209, 'Ácido cítrico 1.22 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (209, 'Ácido tartárico 1.22 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (209, 'Bicarbonato de sodio 12.22 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (209, 'Excipiente C.B.P. 15 g', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Vitamina A (palmitato) 50,000 u.i.', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Vitamina D2 (ergocalciferol) 5,000 u.i.', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Vitamina C (ascorbato de sodio) 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Vitamina E 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Vitamina B1 (clorhidrato de tiamina) 50 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Vitamina B6 (clorhidrato de piridoxina) 10 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Vitamina B2 (clorhidrato de riboflavina) 20 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Glicerofosfato de calcio 250 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Sericographis mohuitle 200 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Calendula officinalis 200 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Polipodium vulgare 50 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (210, 'Achillea millefolium 50 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Vitamina A (palmitato) 50,000 u.i.', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Vitamina D2 (ergocalciferol) 5,000 u.i.', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Vitamina C (ascorbato de sodio) 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Vitamina E 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Vitamina B1 (clorhidrato de tiamina) 50 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Vitamina B6 (clorhidrato de piridoxina) 10 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Vitamina B2 (clorhidrato de riboflavina) 20 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Glicerofosfato de calcio 250 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Turnera difusa 500 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Petrosenilum sativum 50 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Angélica archangelica 30 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (211, 'Aristolochia grandiflora 30 mg', '');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (212, '', 'Lavanda');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (212, '', 'Canela');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (212, '', 'Eucalipto');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (212, '', 'Menta');
INSERT INTO complement_db.ingredients (productId, scientificName, commonName) VALUES (212, '', 'Alcanfor');

UPDATE
    complement_db.ingredients
SET
    scientificName = CASE scientificName WHEN '' THEN NULL ELSE scientificName END,
    commonName = CASE commonName WHEN '' THEN NULL ELSE commonName END