INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 1, 'Depresión Reactiva');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 1, 'Depresión Unipolar Y Bipolar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 2, 'Depresión Reactiva');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 2, 'Depresión Unipolar Y Bipolar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 4, 'Parkinson');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 5, 'Jaquecas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 5, 'Migraña');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 6, 'Ansiedad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 6, 'Depresión Reactiva');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 6, 'Depresión Unipolar Y Bipolar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 6, 'Estrés');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 6, 'Gastritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 6, 'Insomnio');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 6, 'Jaquecas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 6, 'Nervios');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 7, 'Ansiedad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 7, 'Astenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 7, 'Concentración Mental');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 7, 'Depresión Reactiva');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 7, 'Depresión Unipolar Y Bipolar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 7, 'Estrés');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 8, 'Insomnio');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 9, 'Epilepsia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 10, 'Jaquecas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 10, 'Migraña');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 11, 'Ansiedad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 11, 'Estrés');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 11, 'Insomnio');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 11, 'Nervios');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 12, 'Jaquecas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 12, 'Migraña');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 13, 'Parkinson');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 14, 'Diabetes');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 15, 'Geriatría');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 15, 'Impotencia Sexual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 15, 'Senilidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 16, 'Diabetes');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 16, 'Geriatría');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 16, 'Hígado');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 16, 'Insuficiencia Hepática');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 16, 'Insuficiencia Renal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 16, 'Pre Menopausia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 16, 'Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 16, 'Tiroides');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 16, 'Vesícula');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 16, 'Vitíligo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 17, 'Glándulas Suprarrenales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 17, 'Vitíligo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 18, 'Psoriasis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 19, 'Diabetes');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 20, 'Acné');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 21, 'Alopecia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 22, 'Blefaritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 22, 'Conjuntivitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 23, 'Alergias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 23, 'Eczemas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 23, 'Eritemas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 23, 'Escozor');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 23, 'Prurito');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 24, 'Dermatosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 24, 'Eczemas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 24, 'Eritemas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 24, 'Prurito');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 24, 'Psoriasis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 25, 'Herpes Genital');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 25, 'Herpes Zoster');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 26, 'Blanqueadora De Cutis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 27, 'Manchas En El Cutis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 28, 'Repelente');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 29, 'Vitíligo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 30, 'Dermatofitosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 31, 'Asma');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 32, 'Asma');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 33, 'Asma');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 34, 'Congestión Respiratoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 34, 'Estimulante De La Respiracion');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 34, 'Inhalaciones');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 35, 'Bronconeumonía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 35, 'Bronquitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 35, 'Enfisema Pulmonar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 35, 'Laringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 35, 'Sinusitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 35, 'Tos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 36, 'Asma Bronquial');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 36, 'Bronconeumonía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 36, 'Bronquitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 36, 'Enfisema Pulmonar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 36, 'Laringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 36, 'Sinusitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 36, 'Tos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 36, 'Tos Ferina');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 37, 'Fiebre');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 37, 'Sudorífico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 38, 'Amigdalitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 38, 'Faringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 38, 'Infecciones Respiratorias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 38, 'Laringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 39, 'Amigdalitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 39, 'Faringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 39, 'Gingivitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 39, 'Infecciones Respiratorias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 39, 'Laringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 40, 'Asma Bronquial');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 40, 'Bronconeumonía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 40, 'Congestión Respiratoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 40, 'Enfisema Pulmonar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 40, 'Faringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 40, 'Infecciones Respiratorias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 40, 'Laringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 40, 'Sinusitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 41, 'Tos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 41, 'Tos Ferina');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 42, 'Congestión Respiratoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 42, 'Disnea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 42, 'Inhalaciones');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 43, 'Asma Bronquial');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 43, 'Tos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 44, 'Fiebre');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 45, 'Amigdalitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 45, 'Faringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 45, 'Laringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 46, 'Congestión Respiratoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 46, 'Mucolítico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 46, 'Sinusitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 47, 'Bronquitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 47, 'Congestión Respiratoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 47, 'Tos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 48, 'Catarro Común');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 48, 'Congestión Respiratoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 49, 'Bronconeumonía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 49, 'Bronquitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 49, 'Tos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 50, 'Bronquitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 50, 'Mucolítico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 50, 'Sinusitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 50, 'Tos Ferina');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 51, 'Tos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 52, 'Alergias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 52, 'Asma');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 52, 'Asma Bronquial');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 53, 'Hipertensión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 54, 'Hipertensión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 55, 'Astenia Neurocirculatoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 55, 'Dolor Precordial');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 55, 'Neurotonia Cardíaca');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 55, 'Palpitaciones cardíacas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 55, 'Taquicardia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 56, 'Cicatrizante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 56, 'Dermatosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 56, 'Hemostático');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 57, 'Astenia Neurocirculatoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 57, 'Ateroma');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 57, 'Hemorroides');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 57, 'Insuficiencia Vascular Cerebral');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 57, 'Isquemia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 57, 'Trombosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 57, 'Úlceras Varicosas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 57, 'Varices');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 58, 'Hipotensión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 59, 'Arterioesclerosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 59, 'Colesterol');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 59, 'Hipercolesterolemia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 59, 'Obesidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 60, 'Hemostático');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 61, 'Hemostático');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 61, 'Metrorragia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 62, 'Hemorroides');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 63, 'Hemorroides');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 64, 'Alzheimer');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 64, 'Concentración Mental');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 64, 'Insuficiencia Vascular Cerebral');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 64, 'Mareos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 64, 'Neurastenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 65, 'Arterioesclerosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 65, 'Concentración Mental');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 65, 'Impotencia Sexual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 65, 'Insuficiencia Vascular Cerebral');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 65, 'Migraña');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 65, 'Neurastenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 66, 'Arterioesclerosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 66, 'Ateroma');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 66, 'Colesterol');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 66, 'Hipercolesterolemia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 66, 'Insuficiencia Vascular Cerebral');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 66, 'Isquemia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 67, 'Hipertensión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 68, 'Infecciones Intestinales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 68, 'Parasitosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 68, 'Salmonelosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 68, 'Tifoidea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 69, 'Isquemia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 69, 'Úlceras Varicosas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 69, 'Varices');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 70, 'Cicatrizante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 70, 'Úlceras Varicosas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 71, 'Varices');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 72, 'Arterioesclerosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 72, 'Colesterol');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 72, 'Hipercolesterolemia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 73, 'Arterioesclerosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 73, 'Colesterol');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 73, 'Hipercolesterolemia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 74, 'Ateroma');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 74, 'Isquemia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 74, 'Úlceras Varicosas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 74, 'Varices');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 75, 'Arterioesclerosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 75, 'Colesterol');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 75, 'Hígado');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 75, 'Hipercolesterolemia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 76, 'Hipertensión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 77, 'Acné');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 77, 'Cálculos Biliares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 77, 'Colesterol');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 77, 'Hígado');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 77, 'Insuficiencia Hepática');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 78, 'Colitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 79, 'Digestión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 79, 'Flatulencias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 79, 'Halitosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 79, 'Hipermotilidad Intestinal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 79, 'Indigestión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 80, 'Mareos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 80, 'Náuseas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 81, 'Mareos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 81, 'Náuseas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 82, 'Colitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 82, 'Diarrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 82, 'Infecciones Intestinales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 82, 'Parasitosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 82, 'Salmonelosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 82, 'Tifoidea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 83, 'Diarrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 83, 'Parasitosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 84, 'Hipermotilidad Intestinal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 84, 'Indigestión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 84, 'Moderador Estomacal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 85, 'Colitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 85, 'Flatulencias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 86, 'Acidosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 86, 'Gastritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 86, 'Hernia Hiatal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 86, 'Hiper Acidez Gástrica');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 86, 'Úlceras Pépticas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 87, 'Hernia Hiatal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 87, 'Úlceras Pépticas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 88, 'Hernia Hiatal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 89, 'Amigdalitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 89, 'Digestión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 89, 'Faringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 89, 'Gingivitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 89, 'Halitosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 89, 'Laringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 90, 'Estreñimiento');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 91, 'Estreñimiento');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 92, 'Colitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 92, 'Digestión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 92, 'Estreñimiento');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 92, 'Flatulencias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 92, 'Gastritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 92, 'Hemorroides');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 92, 'Peso (Reductor)');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 92, 'Úlceras Pépticas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 93, 'Acné');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 93, 'Eczemas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 93, 'Hígado');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 93, 'Insuficiencia Hepática');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 93, 'Insuficiencia Renal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 93, 'Purificación Sanguínea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 94, 'Anticolinérgico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 94, 'Antiespasmódico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 94, 'Diarrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 96, 'Diarrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 96, 'Hipermotilidad Intestinal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 97, 'Diarrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 97, 'Hipermotilidad Intestinal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 98, 'Cálculos Biliares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 98, 'Colagogo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 98, 'Hígado');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 98, 'Vesícula');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 99, 'Diarrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 99, 'Parasitosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 100, 'Colagogo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 100, 'Hígado');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 100, 'Vesícula');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 101, 'Hígado');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 101, 'Insuficiencia Hepática');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 101, 'Purificación Sanguínea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 102, 'Alimentación');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 102, 'Anemias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 102, 'Energético');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 102, 'Vigorizante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 103, 'Anorexia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 103, 'Inapetencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 104, 'Anemias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 104, 'Deficiencias Vitamínicas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 104, 'Eritropoyetico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 105, 'Anemias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 105, 'Avitaminosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 105, 'Deficiencias Vitamínicas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 105, 'Desnutrición');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 106, 'Obesidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 106, 'Peso (Reductor)');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 107, 'Alimentación');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 107, 'Astenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 107, 'Desnutrición');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 107, 'Impotencia Sexual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 108, 'Concentración Mental');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 108, 'Hemorroides');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 108, 'Impotencia Sexual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 108, 'Neurastenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 108, 'Senilidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 108, 'Varices');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 109, 'Antioxidante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 109, 'Baja Inmunidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 110, 'Alimentación');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 110, 'Astenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 111, 'Avitaminosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 111, 'Deficiencias Vitamínicas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 111, 'Energético');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 111, 'Vigorizante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 112, 'Astenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 112, 'Deficiencias Vitamínicas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 112, 'Inapetencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 112, 'Vigorizante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (11, 113, 'Avitaminosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 114, 'Cáncer De Mama');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 114, 'Neoplasia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 114, 'Neuroblastoma');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 114, 'Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 114, 'Quistes En El Pecho');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 114, 'Quistes Ováricos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 114, 'Sarcomas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 114, 'Vejiga');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 115, 'Antioxidante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 115, 'Baja Inmunidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 115, 'Digestión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 115, 'Halitosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 115, 'Inmunodeficiencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 116, 'Infecciones Intestinales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 116, 'Inmunodeficiencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 116, 'Laringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 116, 'Tifoidea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 116, 'Tos Ferina');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 117, 'Oxidación');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 118, 'Baja Inmunidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 118, 'Inmunodeficiencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 119, 'Quistes En El Pecho');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 119, 'Tumores En Crecimiento');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 120, 'Quistes Ováricos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 120, 'Tumores En Crecimiento');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 121, 'Cáncer De Mama');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 121, 'Inmunodeficiencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 121, 'Neoplasia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 121, 'Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 121, 'Purificación Sanguínea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 121, 'Quistes En El Pecho');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 121, 'Sarcomas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 122, 'Cáncer De Mama');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 122, 'Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 122, 'Quistes En El Pecho');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 122, 'Sarcomas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 122, 'Tumores En Crecimiento');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 123, 'Herpes Zoster');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 123, 'Infecciones Intestinales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 123, 'Salmonelosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 123, 'Tifoidea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 124, 'Infecciones Respiratorias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 125, 'Infecciones Dérmicas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 126, 'Baja Inmunidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 126, 'Inmunodeficiencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 127, 'Adenosarcoma De Ovario');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 127, 'Amenorrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 127, 'Dismenorrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 127, 'Menstruación');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 127, 'Metrorragia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 127, 'Síndrome Pre Menstrual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 128, 'Impotencia Sexual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 129, 'Impotencia Sexual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 129, 'Senilidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 130, 'Amenorrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 130, 'Menstruación');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 131, 'Cálculos Renales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 131, 'Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 131, 'Uretritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 132, 'Insuficiencia Renal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 132, 'Pielonefritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 132, 'Uretritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 132, 'Vaginitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 133, 'Ácido Úrico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 133, 'Edema');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 133, 'Gota');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 133, 'Hidropesía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 133, 'Insuficiencia Renal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 134, 'Cálculos Biliares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 134, 'Cálculos Renales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 134, 'Insuficiencia Renal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 134, 'Pielonefritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 134, 'Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 134, 'Uretritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 135, 'Cálculos Biliares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 135, 'Cálculos Renales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 135, 'Insuficiencia Renal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 135, 'Pielonefritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 135, 'Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 135, 'Uretritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 136, 'Uretritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 136, 'Vaginitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 137, 'Impotencia Sexual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 138, 'Ciática');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 138, 'Contusiones');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 138, 'Fracturas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 138, 'Inflamación');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 138, 'Tonosinovitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 139, 'Artritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 139, 'Artrosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 139, 'Reumatismo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 139, 'Reumatismo Crónico Deformante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 140, 'Artritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 140, 'Artrosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 140, 'Ciática');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 140, 'Contusiones');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 140, 'Distenciones Musculares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 140, 'Esguinces');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 140, 'Fracturas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 140, 'Inflamación');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 140, 'Lumbago');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 140, 'Reumatismo Crónico Deformante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 141, 'Ácido Úrico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 141, 'Artritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 141, 'Artrosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 141, 'Bursitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 141, 'Lumbago');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 141, 'Mialgias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 141, 'Reumatismo Crónico Deformante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 142, 'Contusiones');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 142, 'Esguinces');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 142, 'Gota');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 142, 'Lumbago');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 142, 'Mialgias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 142, 'Tonosinovitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 143, 'Artritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 143, 'Contusiones');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 143, 'Distenciones Musculares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 143, 'Esguinces');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 143, 'Reumatismo Crónico Deformante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 144, 'Fracturas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 144, 'Osteoporosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 145, 'Contusiones');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 145, 'Distenciones Musculares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 145, 'Esguinces');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 145, 'Lumbago');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 145, 'Tonosinovitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 146, 'Ácido Úrico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 146, 'Gota');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 146, 'Reumatismo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 146, 'Reumatismo Crónico Deformante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 147, 'Artritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 147, 'Reumatismo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 148, 'Artrosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 148, 'Reumatismo Crónico Deformante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 149, 'Astenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 149, 'Celulitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 149, 'Deficiencias Vitamínicas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 149, 'Desnutrición');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 149, 'Eritropoyetico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 149, 'Fibromialgia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 149, 'Fracturas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 149, 'Hernia Discal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 149, 'Hiper Acidez Gástrica');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 149, 'Peso (Reductor)');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 149, 'Senilidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 150, 'Astenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 150, 'Depresión Reactiva');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 150, 'Depresión Unipolar Y Bipolar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 150, 'Estimulante Funcional');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 151, 'Depresión Reactiva');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 151, 'Depresión Unipolar Y Bipolar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 151, 'Energético');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 151, 'Estimulante Funcional');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 152, 'Alopecia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 152, 'Astenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 152, 'Neurastenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 152, 'Senilidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 152, 'Timo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 152, 'Vigorizante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 153, 'Concentración Mental');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 153, 'Depresión Reactiva');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 153, 'Depresión Unipolar Y Bipolar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 153, 'Estimulante Físico-Mental');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 153, 'Estrés');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 154, 'Astenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 154, 'Energético');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 154, 'Estimulante Funcional');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 154, 'Vigorizante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 155, 'Depresión Reactiva');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 155, 'Depresión Unipolar Y Bipolar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 155, 'Energético');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 155, 'Estimulante Funcional');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (3, 155, 'Vigorizante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 156, 'Anemias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 156, 'Avitaminosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 157, 'Estreñimiento');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 157, 'Gastritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 158, 'Menopausia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 158, 'Osteoporosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 158, 'Pre Menopausia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 158, 'Quistes Ováricos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 158, 'Síndrome Pre Menstrual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 159, 'Antioxidante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 159, 'Baja Inmunidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 160, 'Impotencia Sexual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 162, 'Inmunodeficiencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 163, 'Inmunodeficiencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 164, 'Desnutrición');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 164, 'Herpes Zoster');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 165, 'Desnutrición');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 166, 'Menopausia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 166, 'Osteoporosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 166, 'Pre Menopausia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 166, 'Quistes Ováricos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 166, 'Síndrome Pre Menstrual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 166, 'Tumores En Crecimiento');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 167, 'Bursitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 167, 'Contusiones');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 167, 'Distenciones Musculares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 167, 'Dolor Precordial');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 167, 'Esguinces');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 167, 'Lumbago');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 167, 'Mialgias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 167, 'Reumatismo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 168, 'Amigdalitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 168, 'Bronconeumonía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 168, 'Faringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 168, 'Infecciones Intestinales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 168, 'Laringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 168, 'Salmonelosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 168, 'Tifoidea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 169, 'Amigdalitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 169, 'Bronconeumonía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 169, 'Faringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 169, 'Infecciones Intestinales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 169, 'Laringitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 169, 'Salmonelosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 169, 'Tifoidea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 170, 'Artritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 170, 'Distenciones Musculares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 170, 'Fracturas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 170, 'Golpes');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 171, 'Enfisema Pulmonar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 172, 'Depresión Reactiva');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 172, 'Depresión Unipolar Y Bipolar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 172, 'Insomnio');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 173, 'Ateroma');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 173, 'Náuseas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 173, 'Sinusitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 173, 'Trombosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 174, 'Diabetes');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 175, 'Artritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 175, 'Asma Bronquial');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 175, 'Dermatitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 175, 'Diabetes');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 175, 'Diarrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 175, 'Dismenorrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 175, 'Eczemas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 175, 'Esguinces');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 175, 'Gastritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 175, 'Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 175, 'Tifoidea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Anemias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Anorexia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Ansiedad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Arterioesclerosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Astenia Neurocirculatoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Avitaminosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Hipertensión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Impotencia Sexual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Inapetencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Neurastenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Senilidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 176, 'Uretritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Anemias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Anorexia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Ansiedad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Arterioesclerosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Astenia Neurocirculatoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Avitaminosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Hipertensión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Impotencia Sexual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Inapetencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Neurastenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Senilidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 177, 'Uretritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 178, 'Alzheimer');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 179, 'Cáncer De Mama');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 179, 'Colesterol');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 179, 'Geriatría');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 179, 'Hígado');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 179, 'Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 179, 'Taquicardia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 179, 'Trombosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 180, 'Artritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 180, 'Artrosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 180, 'Bursitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 180, 'Ciática');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 180, 'Distenciones Musculares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 180, 'Esguinces');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 180, 'Gota');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 180, 'Hernia Discal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 180, 'Reumatismo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 181, 'Artritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 181, 'Artrosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 181, 'Bursitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 181, 'Ciática');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 181, 'Distenciones Musculares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 181, 'Esguinces');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 181, 'Gota');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 181, 'Hernia Discal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 181, 'Reumatismo');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 182, 'Eritropoyetico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 182, 'Hígado');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 182, 'Obesidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 182, 'Senilidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (9, 183, 'Fibromialgia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 184, 'Acidosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 184, 'Acné');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 184, 'Baja Inmunidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 184, 'Halitosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 184, 'Hernia Hiatal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 184, 'Hiper Acidez Gástrica');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 184, 'Insuficiencia Hepática');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 184, 'Insuficiencia Renal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 184, 'Pielonefritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 184, 'Úlceras Pépticas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 184, 'Úlceras Varicosas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 185, 'Cáncer De Mama');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 185, 'Neoplasia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 185, 'Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 185, 'Quistes En El Pecho');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 185, 'Quistes Ováricos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 185, 'Vejiga');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 186, 'Obesidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 186, 'Peso (Reductor)');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 187, 'Baja Inmunidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 187, 'Inmunodeficiencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 188, 'Baja Inmunidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 188, 'Inmunodeficiencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 189, 'Anorexia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 189, 'Deficiencias Vitamínicas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 189, 'Eritropoyetico');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 189, 'Hígado');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 189, 'Inapetencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 189, 'Nervios');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 189, 'Tiroides');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 189, 'Vesícula');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 189, 'Vigorizante');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 190, 'Adenosarcoma De Ovario');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 190, 'Cáncer De Mama');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 190, 'Linfosarcomas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 190, 'Neuroblastoma');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 190, 'Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (8, 190, 'Quistes En El Pecho');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 191, 'Diabetes');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 192, 'Alzheimer');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 192, 'Diabetes Tipo 2');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 192, 'Obesidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 192, 'Presión Arterial Alta');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 193, 'Menopausia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 194, 'Desarreglos Intestinales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 194, 'Diarrea');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 194, 'Dolores Lumbares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 194, 'Endometriosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 194, 'Estreñimiento');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 194, 'Sensibilidad En Senos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 195, 'Mononeuropatía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 195, 'Mononeuropatía Múltiple O Multifocal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 195, 'Neuropatía Diabética');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 195, 'Polineuropatía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 196, 'Afectación En El Metabolismo Celular');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 196, 'Vejez Prematura');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 197, 'Bradicardia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 197, 'Taquicardia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 198, 'Coledocolitiasis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (5, 198, 'Colelitiasis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 199, 'Insuficiencia Intrarrenal U Orgánica');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 199, 'Insuficiencia Postrrenal U Obstructiva');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 199, 'Insuficiencia Renal, Prerrenal O Funcional');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 200, 'Déficit De Melatonina');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 200, 'Depresión Severa');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 200, 'Insomnio');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 201, 'Anorexia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 201, 'Apatía Sexual');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 201, 'Bajo Tono Muscular');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 201, 'Deficiencia En La Producción Hormonal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 201, 'Déficit De Atención');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 201, 'Dilatación De Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 201, 'Nictalopía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 201, 'Testosterona Y Progesterona');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 202, 'Artritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 202, 'Estreñimiento');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 202, 'Hipertensión');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 202, 'Neuropatía Diabética');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 202, 'Problemas Metabólicos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (1, 202, 'Resfriados');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 203, 'Neuropatía Diabética');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Acné');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Alergias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Alopecia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Artritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Caspa');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Dolor De Cuello');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Dolores Musculares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Eczemas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Hemorroides');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Infecciones Dérmicas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Infecciones Vaginales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Nervios Dolorosos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Paperas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Picaduras De Insectos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Pie De Atleta');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Psoriasis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Quemaduras');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (2, 204, 'Varices');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Anemias');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Arterioesclerosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Celiaquía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Colitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Debilidad Inmunológica');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Diabetes');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Dispepsia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Diverticulosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Estreñimiento');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Gastritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Hipertensión Arterial');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Obesidad');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Obstrucción Intestinal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Plaquetas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Pólipos Intestinales');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Tonificante Cardíaco');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 205, 'Úlceras Pépticas');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 206, 'Colitis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 206, 'Demencia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 206, 'Diabetes Tipo 2');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 206, 'Enfermedad De Crohn');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 206, 'Enfermedades Cardiovasculares');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 206, 'Esquizofrenia');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 206, 'Fibrosis Quística');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (4, 206, 'Trastorno Bipolar');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 207, 'Cáncer Colorrectal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 207, 'Cáncer De Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 207, 'Diverticulosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 207, 'Endometriosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 207, 'Enfermedad Pélvica Inflamatoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 207, 'Fibromas Uterinos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 207, 'Hernia Intestinal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 207, 'Inflamación De La Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 207, 'Inflamación Intestinal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 207, 'Metástasis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 207, 'Uretritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 208, 'Cáncer Colorrectal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 208, 'Cáncer De Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 208, 'Diverticulosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 208, 'Endometriosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 208, 'Enfermedad Pélvica Inflamatoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 208, 'Fibromas Uterinos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 208, 'Hernia Intestinal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 208, 'Inflamación De La Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 208, 'Inflamación Intestinal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 208, 'Metástasis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 208, 'Uretritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 209, 'Cáncer Colorrectal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 209, 'Cáncer De Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 209, 'Diverticulosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 209, 'Endometriosis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 209, 'Enfermedad Pélvica Inflamatoria');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 209, 'Fibromas Uterinos');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 209, 'Hernia Intestinal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 209, 'Inflamación De La Próstata');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 209, 'Inflamación Intestinal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 209, 'Metástasis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (6, 209, 'Uretritis');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 210, 'Desequilibrio Hormonal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 210, 'Menstruación');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (7, 211, 'Desequilibrio Hormonal');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 212, 'Asma Bronquial');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 212, 'Bronconeumonía');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 212, 'Gripa');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (12, 212, 'Trastornos Respiratorios');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 213, 'Epilepsia Idiopática');
INSERT INTO complement_db.sufferings (categoryId, productId, name) VALUES (10, 213, 'Epilepsia Sintomática');